Issues/19 add detail page
SOunit/job_search_app_front pull request #27
Opened 2022-03-02 20:48 UTC by azar-barfipour

I added detail page for each job, when click on the job, the page shows. For now except title, other data are dummy.

2022-03-02 21:24 UTC, SOunit requested changes
thanks for contribution!

I added some comments to fix!

2022-03-02 21:24 UTC, SOunit commented on src/pages/job-detail.js
> +  const [jobDetailList, setJobDetailList] = useState([]);
job detail page has single job right?
so `[jobDetail, setJobDetail]` may be better.

2022-03-02 21:24 UTC, SOunit commented on src/pages/job-detail.js
> +    const fetchJobDetails = async () => {
same.
job detail should be single.

2022-03-02 21:24 UTC, SOunit commented on src/pages/job-detail.js
> +        console.log(data.job);
please delete log.

2022-03-02 21:24 UTC, SOunit commented on src/pages/job-detail.js
> +  return <JobDetailItem jobDetailList={jobDetailList} />;
prop could be `jobDetail`

2022-03-02 21:24 UTC, SOunit commented on src/components/organisms/job-detail/job-detail-item.js
> +const DUMMIDATA = [
variable name `DUMMY_DATA` is better?

2022-03-02 21:24 UTC, SOunit commented on src/components/organisms/job-detail/job-detail-item.js
> +  return (
may i ask you to spread props?
`(props)` => `({jobDataList})`

2022-03-02 21:24 UTC, SOunit commented on src/components/organisms/job-detail/job-detail-item.js
> +  return (
props name could be `jobDetail`

2022-03-02 21:24 UTC, SOunit commented on src/components/organisms/job-detail/job-detail-item.js
> +const DUMMIDATA = [
let's create `dummy-data.js` in `src/components/test` and import the data from outer file

2022-03-02 21:24 UTC, SOunit commented on src/components/organisms/job-detail/job-detail-item.js
> +    <li className={classes["jobDetail-item"]}>
its single item so i guess we can delete li tag

2022-03-02 21:24 UTC, SOunit commented on src/components/organisms/job-list/job-card.js
> +      <Link
is it possible to wrap card with link?
so that all card is touchable.

2022-03-02 21:24 UTC, SOunit commented on src/components/organisms/job-list/job-card.js
> +      <Link
```
<Link
        to={`/jobs/detail/${props.job.id}`}
        className={classes[`${componentName}-link`]}
      >
```

2022-03-02 23:19 UTC, azar-barfipour commented on src/components/organisms/job-detail/job-detail-item.js
> +const DUMMIDATA = [
Aren't we use actual data soon ?

2022-03-02 23:21 UTC, azar-barfipour commented on src/components/organisms/job-list/job-card.js
> +      <Link
I did that but it makes the like button link too. which is not correct

2022-03-03 18:21 UTC, SOunit approved these changes

2022-03-03 18:21 UTC, SOunit commented on src/components/organisms/job-detail/job-detail-item.js
> +const DUMMIDATA = [
sorry i have no time to setup another data, so let's use dummy data for now!

2022-03-03 18:21 UTC, SOunit commented on src/components/organisms/job-list/job-card.js
> +      <Link
ok, then let's keep it as it is!

2022-03-03 18:22 UTC, SOunit approved these changes

2022-03-03 18:23 UTC, merged